name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: danielleedxdocker/memos_time:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le

